# Generated by Django 4.1.5 on 2023-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_userprogress_documentarysector'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentary',
            name='thumbnail',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
